### PR TITLE
Apply good practices to make SS apps require'able/callable and forkable.

### PR DESCRIPTION
**Pull request by rngadam**
Improve testability by using OS assigned port.
Fix two globals leak (detected by mocha).
Add a three tests test suite.
Provide a way to pass actual app current directory;
don't assume our cwd is the right one.
Modify package.json to run mocha on tests.

### CODE REVIEW

**Comment by rngadam** [comment]
Owen, is this not to your taste?

**Comment by owenb** [comment]
Apologies. Been so busy. I will take a look soon!

Thanks for submitting :)

**Comment by owenb** [comment]
Hey Ricky

Sorry for the delay. Finally had time to have a good look at this.

Wow - some nice ideas here.

Can you tell me more about the idea of forking an app? I'm not totally against introducing the additional complexity of

``` js
function main(cb) {
}
```

in the example app, but I need to fully understand the use cases here - apart from for testing using child_process (which is valuable, I agree).

Again, sorry for the delay. Although things are still a bit busier than normal at the moment, I have more time to work on SocketStream now than I did a few weeks ago.

Cheers,

Owen

**Comment by rngadam** [comment]
It's a practice inherited from writing python code, where it's more common.
Given the testing benefit alone, it should become standard practice in the
nodejs world.

In addition to the testing, I've used this approach in my own app to edit
and launch apps from inside a main controller  using the interpreter fork.
That fork has less overhead than running from the commandline.

**Comment by owenb** [comment]
Hey

I'm going to merge this in because I like everything you've done apart from the

``` js
function main(cb) {
}
```

bit which I need to be convinced about. That may happen in the future, but for now I'll merge this in and return app.js to as it was.

Many thanks!

Owen

**Comment by rngadam** [comment]
Thanks Owen!

**Comment by owenb** [comment]
Also going to revert the random port too. I prefer fixing this at 3000, both personally and because it helps with documentation. It's easy enough to change if you want to

**Pull request merged**
